name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening an issue in our repository! 🎉 Please make sure to provide detailed information about the issue you're facing, including any error messages or steps to reproduce. This will help us understand and address the problem more effectively. If you have any questions or need assistance, don't hesitate to ask. We're here to help!"
        pr-message: "Thank you for raising a new pull request! 🚀 Before submitting your pull request, please ensure that you have thoroughly tested your changes and followed our contribution guidelines. This includes providing a clear description of your changes and any related issues or feature requests. If you have any questions or need guidance, feel free to reach out to us. We appreciate your contributions!"
